#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9.2 effective-4.1.50 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
#ifndef ADWHALESDK_SWIFT_H
#define ADWHALESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import GoogleMobileAds;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AdWhaleSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
typedef SWIFT_ENUM(NSInteger, AdWhaleAdSize, open) {
  AdWhaleAdSizeBanner = 0,
  AdWhaleAdSizeLargeBanner = 1,
  AdWhaleAdSizeMediumRectangle = 2,
  AdWhaleAdSizeFullBanner = 3,
  AdWhaleAdSizeLeaderboard = 4,
};

@class NSString;
@class UIViewController;
enum AdWhaleLogLevel : NSInteger;
@class GADRequest;

SWIFT_CLASS("_TtC10AdWhaleSDK10AdWhaleAds")
@interface AdWhaleAds : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AdWhaleAds * _Nonnull sharedInstance;)
+ (AdWhaleAds * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (void)initializeWithAppId:(NSString * _Nonnull)appId rootViewController:(UIViewController * _Nonnull)rootViewController completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)initializeWithAppId:(NSString * _Nonnull)appId rootViewController:(UIViewController * _Nonnull)rootViewController useGdpr:(BOOL)useGdpr testDevices:(NSArray<NSString *> * _Nullable)testDevices completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)resetGDPRWithCompletionHandler:(void (^ _Nonnull)(void))completionHandler;
- (BOOL)canShowAds SWIFT_WARN_UNUSED_RESULT;
- (void)setLogLevelWithLogLevel:(enum AdWhaleLogLevel)logLevel;
- (GADRequest * _Nullable)AdWhaleRequest SWIFT_WARN_UNUSED_RESULT;
- (void)setTestDeviceIdentifiersWithTestDeviceIdentifiers:(NSString * _Nonnull)testDeviceIdentifiers;
- (void)showAdInspectorWithViewController:(UIViewController * _Nonnull)viewController;
- (void)showAdInspectorWithViewController:(UIViewController * _Nonnull)viewController completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
@end

@protocol AdWhaleAppOpenAdViewDelegate;
@protocol AdWhaleAppOpenAdDelegate;

SWIFT_CLASS("_TtC10AdWhaleSDK16AdWhaleAppOpenAd")
@interface AdWhaleAppOpenAd : NSObject
@property (nonatomic, weak) id <AdWhaleAppOpenAdViewDelegate> _Nullable appOpenAdViewDelegate;
@property (nonatomic, weak) id <AdWhaleAppOpenAdDelegate> _Nullable appOpenAdDelegate;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AdWhaleAppOpenAd * _Nonnull shared;)
+ (AdWhaleAppOpenAd * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (void)loadAd:(NSString * _Nonnull)adUnitId;
- (void)showAdIfAvailable:(UIViewController * _Nonnull)viewController;
@end

@protocol GADFullScreenPresentingAd;

@interface AdWhaleAppOpenAd (SWIFT_EXTENSION(AdWhaleSDK)) <GADFullScreenContentDelegate>
- (void)adWillPresentFullScreenContent:(id <GADFullScreenPresentingAd> _Nonnull)ad;
- (void)adDidDismissFullScreenContent:(id <GADFullScreenPresentingAd> _Nonnull)ad;
- (void)ad:(id <GADFullScreenPresentingAd> _Nonnull)ad didFailToPresentFullScreenContentWithError:(NSError * _Nonnull)error;
@end


SWIFT_PROTOCOL("_TtP10AdWhaleSDK24AdWhaleAppOpenAdDelegate_")
@protocol AdWhaleAppOpenAdDelegate
- (void)adDidReceiveAd;
- (void)adWillPresentFullScreenContent;
- (void)adDidDismissFullScreenContent;
- (void)adDidFailToPresentFullScreenContentWithError:(NSError * _Nonnull)error;
@end


SWIFT_PROTOCOL("_TtP10AdWhaleSDK28AdWhaleAppOpenAdViewDelegate_")
@protocol AdWhaleAppOpenAdViewDelegate
- (void)appOpenAdDidComplete:(AdWhaleAppOpenAd * _Nonnull)ad;
@end

@class NSCoder;
@protocol AdWhaleBannerDelegate;
@class GADBannerView;

SWIFT_CLASS("_TtC10AdWhaleSDK15AdWhaleBannerAd")
@interface AdWhaleBannerAd : UIView <GADBannerViewDelegate>
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(enum AdWhaleAdSize)adSize OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)setAdUnitID:(NSString * _Nonnull)adUnitID;
- (void)setAdSize:(enum AdWhaleAdSize)adSize;
- (void)setDelegate:(id <AdWhaleBannerDelegate> _Nonnull)delegate;
- (void)setRootViewController:(UIViewController * _Nonnull)rootViewController;
- (void)load;
- (void)bannerViewDidReceiveAd:(GADBannerView * _Nonnull)bannerView;
- (void)bannerView:(GADBannerView * _Nonnull)bannerView didFailToReceiveAdWithError:(NSError * _Nonnull)error;
- (void)bannerViewDidRecordImpression:(GADBannerView * _Nonnull)bannerView;
- (void)bannerViewWillPresentScreen:(GADBannerView * _Nonnull)bannerView;
- (void)bannerViewWillDismissScreen:(GADBannerView * _Nonnull)bannerView;
- (void)bannerViewDidDismissScreen:(GADBannerView * _Nonnull)bannerView;
@end


SWIFT_PROTOCOL("_TtP10AdWhaleSDK21AdWhaleBannerDelegate_")
@protocol AdWhaleBannerDelegate
- (void)bannerViewDidReceiveAd:(AdWhaleBannerAd * _Nonnull)bannerView;
- (void)bannerView:(AdWhaleBannerAd * _Nonnull)bannerView didFailToReceiveAdWithError:(NSError * _Nonnull)error;
- (void)bannerViewDidRecordImpression:(AdWhaleBannerAd * _Nonnull)bannerView;
- (void)bannerViewWillPresentScreen:(AdWhaleBannerAd * _Nonnull)bannerView;
- (void)bannerViewWillDismissScreen:(AdWhaleBannerAd * _Nonnull)bannerView;
- (void)bannerViewDidDismissScreen:(AdWhaleBannerAd * _Nonnull)bannerView;
@end

typedef SWIFT_ENUM(NSInteger, AdWhaleGdprType, open) {
  AdWhaleGdprTypePopupLocation = 0,
  AdWhaleGdprTypePopupDebug = 1,
  AdWhaleGdprTypeDirectNotRequired = 2,
};

@protocol AdWhaleInterstitialDelegate;

SWIFT_CLASS("_TtC10AdWhaleSDK21AdWhaleInterstitialAd")
@interface AdWhaleInterstitialAd : NSObject
@property (nonatomic, strong) id <AdWhaleInterstitialDelegate> _Nullable interstitialDelegate;
- (void)load:(NSString * _Nonnull)adUnitId;
- (void)show:(UIViewController * _Nonnull)rootViewController;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface AdWhaleInterstitialAd (SWIFT_EXTENSION(AdWhaleSDK)) <GADFullScreenContentDelegate>
- (void)ad:(id <GADFullScreenPresentingAd> _Nonnull)ad didFailToPresentFullScreenContentWithError:(NSError * _Nonnull)error;
/// Tells the delegate that the ad will present full screen content.
- (void)adWillPresentFullScreenContent:(id <GADFullScreenPresentingAd> _Nonnull)ad;
/// Tells the delegate that the ad dismissed full screen content.
- (void)adDidDismissFullScreenContent:(id <GADFullScreenPresentingAd> _Nonnull)ad;
@end


SWIFT_PROTOCOL("_TtP10AdWhaleSDK27AdWhaleInterstitialDelegate_")
@protocol AdWhaleInterstitialDelegate
- (void)adDidReceiveAd:(AdWhaleInterstitialAd * _Nonnull)ad;
- (void)adDidFailToReceiveAdWithError:(NSError * _Nonnull)error;
- (void)ad:(AdWhaleInterstitialAd * _Nonnull)ad didFailToPresentFullScreenContentWithError:(NSError * _Nonnull)error;
/// Tells the delegate that the ad will present full screen content.
- (void)adWillPresentFullScreenContent:(AdWhaleInterstitialAd * _Nonnull)ad;
/// Tells the delegate that the ad dismissed full screen content.
- (void)adDidDismissFullScreenContent:(AdWhaleInterstitialAd * _Nonnull)ad;
@end

typedef SWIFT_ENUM(NSInteger, AdWhaleLogLevel, open) {
  AdWhaleLogLevelError = 0,
  AdWhaleLogLevelNotice = 1,
  AdWhaleLogLevelInfo = 2,
  AdWhaleLogLevelDebug = 3,
};


SWIFT_CLASS("_TtC10AdWhaleSDK16AdWhaleMediaView")
@interface AdWhaleMediaView : GADMediaView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AdWhaleSDK15AdWhaleNativeAd")
@interface AdWhaleNativeAd : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol AdWhaleNativeAdLoaderDelegate;
enum AdWhaleNativeAspectRatio : NSInteger;
@class TestNativeAdView;
@class AdWhaleNativeAdView;

SWIFT_CLASS("_TtC10AdWhaleSDK21AdWhaleNativeAdLoader")
@interface AdWhaleNativeAdLoader : NSObject
@property (nonatomic, strong) id <AdWhaleNativeAdLoaderDelegate> _Nullable delegate;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AdWhaleNativeAdLoader * _Nonnull sharedInstance;)
+ (AdWhaleNativeAdLoader * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (void)initializeWithAdUnitId:(NSString * _Nonnull)adUnitId rootViewController:(UIViewController * _Nonnull)rootViewController;
- (void)initializeWithAdUnitId:(NSString * _Nonnull)adUnitId rootViewController:(UIViewController * _Nonnull)rootViewController aspectRatioOption:(enum AdWhaleNativeAspectRatio)aspectRatioOption;
- (void)loadAd;
- (void)setTestRenderingViewClass:(NSString * _Nonnull)adUnitId nativeAdView:(TestNativeAdView * _Nonnull)nativeAdView;
- (void)setRenderingViewClassWithNativeAdView:(AdWhaleNativeAdView * _Nonnull)nativeAdView;
@end

@class GADAdLoader;
@class GADNativeAd;

@interface AdWhaleNativeAdLoader (SWIFT_EXTENSION(AdWhaleSDK)) <GADNativeAdDelegate, GADNativeAdLoaderDelegate>
- (void)adLoader:(GADAdLoader * _Nonnull)adLoader didReceiveNativeAd:(GADNativeAd * _Nonnull)nativeAd;
- (void)adLoader:(GADAdLoader * _Nonnull)adLoader didFailToReceiveAdWithError:(NSError * _Nonnull)error;
- (void)nativeAdDidRecordImpression:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdDidRecordClick:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdWillPresentScreen:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdWillDismissScreen:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdDidDismissScreen:(GADNativeAd * _Nonnull)nativeAd;
@end


SWIFT_PROTOCOL("_TtP10AdWhaleSDK29AdWhaleNativeAdLoaderDelegate_")
@protocol AdWhaleNativeAdLoaderDelegate
- (void)nativeAdLoaderDidReceiveAd:(AdWhaleNativeAd * _Nonnull)nativeAd;
- (void)nativeAdLoaderDidFailToReceiveAd:(AdWhaleNativeAdLoader * _Nonnull)nativeAd error:(NSError * _Nonnull)error;
@end


SWIFT_CLASS("_TtC10AdWhaleSDK19AdWhaleNativeAdView")
@interface AdWhaleNativeAdView : GADNativeAdView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, AdWhaleNativeAspectRatio, open) {
  AdWhaleNativeAspectRatioLandscape = 0,
  AdWhaleNativeAspectRatioSquare = 1,
  AdWhaleNativeAspectRatioPortrait = 2,
  AdWhaleNativeAspectRatioAny = 3,
};


SWIFT_CLASS("_TtC10AdWhaleSDK13AdWhaleReward")
@interface AdWhaleReward : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@protocol AdWhaleRewardDelegate;

SWIFT_CLASS("_TtC10AdWhaleSDK15AdWhaleRewardAd")
@interface AdWhaleRewardAd : NSObject <GADFullScreenContentDelegate>
@property (nonatomic, strong) id <AdWhaleRewardDelegate> _Nullable rewardDelegate;
- (void)load:(NSString * _Nonnull)adUnitId;
- (void)show:(UIViewController * _Nonnull)rootViewController;
- (void)ad:(id <GADFullScreenPresentingAd> _Nonnull)ad didFailToPresentFullScreenContentWithError:(NSError * _Nonnull)error;
/// Tells the delegate that the ad will present full screen content.
- (void)adWillPresentFullScreenContent:(id <GADFullScreenPresentingAd> _Nonnull)ad;
/// Tells the delegate that the ad dismissed full screen content.
- (void)adDidDismissFullScreenContent:(id <GADFullScreenPresentingAd> _Nonnull)ad;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP10AdWhaleSDK21AdWhaleRewardDelegate_")
@protocol AdWhaleRewardDelegate
- (void)adDidReceiveRewardAd:(AdWhaleRewardAd * _Nonnull)ad;
- (void)adDidEarnReward:(AdWhaleReward * _Nonnull)reward;
- (void)adDidFailToReceiveRewardAdWithError:(NSError * _Nonnull)error;
- (void)ad:(AdWhaleRewardAd * _Nonnull)ad didFailToPresentRewardAdWithError:(NSError * _Nonnull)error;
/// Tells the delegate that the ad will present full screen content.
- (void)adWillPresentRewardAd:(AdWhaleRewardAd * _Nonnull)ad;
/// Tells the delegate that the ad dismissed full screen content.
- (void)adDidDismissRewardAd:(AdWhaleRewardAd * _Nonnull)ad;
@end

typedef SWIFT_ENUM(NSInteger, TestAdWhaleAdSize, open) {
  TestAdWhaleAdSizeBanner = 0,
  TestAdWhaleAdSizeLargeBanner = 1,
  TestAdWhaleAdSizeMediumRectangle = 2,
};


SWIFT_CLASS("_TtC10AdWhaleSDK12TestNativeAd")
@interface TestNativeAd : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol TestNativeAdLoaderDelegate;

SWIFT_CLASS("_TtC10AdWhaleSDK18TestNativeAdLoader")
@interface TestNativeAdLoader : NSObject
@property (nonatomic, strong) id <TestNativeAdLoaderDelegate> _Nullable delegate;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) TestNativeAdLoader * _Nonnull sharedInstance;)
+ (TestNativeAdLoader * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (void)initializeWithAdUnitId:(NSString * _Nonnull)adUnitId rootViewController:(UIViewController * _Nonnull)rootViewController;
- (void)loadAd;
- (void)setNativeAdView:(TestNativeAdView * _Nonnull)nativeAdView adPlaceholder:(UIView * _Nonnull)adPlaceholder;
@end


@interface TestNativeAdLoader (SWIFT_EXTENSION(AdWhaleSDK)) <GADNativeAdDelegate, GADNativeAdLoaderDelegate>
- (void)adLoader:(GADAdLoader * _Nonnull)adLoader didReceiveNativeAd:(GADNativeAd * _Nonnull)nativeAd;
- (void)adLoader:(GADAdLoader * _Nonnull)adLoader didFailToReceiveAdWithError:(NSError * _Nonnull)error;
- (void)nativeAdDidRecordImpression:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdDidRecordClick:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdWillPresentScreen:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdWillDismissScreen:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdDidDismissScreen:(GADNativeAd * _Nonnull)nativeAd;
@end


SWIFT_PROTOCOL("_TtP10AdWhaleSDK26TestNativeAdLoaderDelegate_")
@protocol TestNativeAdLoaderDelegate
- (void)nativeAdLoaderDidReceiveAd:(TestNativeAd * _Nonnull)nativeAd;
- (void)nativeAdLoaderDidFailToReceiveAd:(TestNativeAdLoader * _Nonnull)nativeAd error:(NSError * _Nonnull)error;
@end

@class UILabel;
@class UIButton;
@class UIImageView;

SWIFT_PROTOCOL("_TtP10AdWhaleSDK21TestNativeAdRendering_")
@protocol TestNativeAdRendering
- (UILabel * _Nullable)adTitleLabel SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nullable)adBodyLabel SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nullable)adCallToActionButton SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nullable)adProfileNameLabel SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nullable)adProfileIconView SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)adMediaView SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nullable)customInfoIconView SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC10AdWhaleSDK16TestNativeAdView")
@interface TestNativeAdView : GADNativeAdView
- (UILabel * _Nullable)adTitleLabel SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nullable)adBodyLabel SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nullable)adCallToActionButton SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nullable)adProfileNameLabel SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nullable)adProfileIconView SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)adMediaView SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nullable)customInfoIconView SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
